### ISSUE TITLE
Generation of plots for CMIP5 fails on the evaluation page

### ISSUE THREAD

**Issue by aspinuso** [ESMValGroup/C4I-Integration#4]
I tried to open the evaluation page from C4I CMIP5 project. See link below.

https://esmvaltool.dkrz.de/shared/esmvaltool/climate4impact/?project=CMIP5&dataset=CanCM4&dataset=HadCM3 

Looks like the plots with the highlighted model are not shown.

**Comment by bouweandela** [comment]
Thanks for reporting @aspinuso. We will have a look and get back to you.

**Comment by Peter9192** [comment]
Fixed in #5. Already deployed, so a hard refresh should fix the issue on your end. Can you verify @bouweandela @aspinuso?
